server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
#    file: myapp.log

spring:
  datasource:
    #    url: jdbc:h2:./hexlet
    url: jdbc:postgresql://localhost:5432/catalog
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger.html

#  liquibase:
#    change-log: classpath:db/changelog/changelog-master.xml
#  h2:
#    console:
#      enabled: true
#      path: /h2console/
#      settings:
#        web-allow-others: true
