server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO

spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/catalog
#    username: postgres
#    password: postgres
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger.html
